/** Бібліотека готових ілюстрацій деки (фото Тетяни, 3D NovaPay, зображення зі слайдів). */
export const DECK_LIBRARY: { src: string; label: string }[] = [
  { src: "/deck/novapay/alex.jpg", label: "alex" },
  { src: "/deck/novapay/boxing.jpg", label: "boxing" },
  { src: "/deck/novapay/clients.png", label: "clients" },
  { src: "/deck/novapay/devito.jpg", label: "devito" },
  { src: "/deck/novapay/discipline.jpg", label: "discipline" },
  { src: "/deck/novapay/einstein.jpg", label: "einstein" },
  { src: "/deck/novapay/giraffe.jpg", label: "giraffe" },
  { src: "/deck/novapay/kid.jpg", label: "kid" },
  { src: "/deck/novapay/madonna.jpg", label: "madonna" },
  { src: "/deck/novapay/matches.jpg", label: "matches" },
  { src: "/deck/novapay/meditation.jpg", label: "meditation" },
  { src: "/deck/novapay/money.png", label: "money" },
  { src: "/deck/novapay/novapay-logo.png", label: "novapay-logo" },
  { src: "/deck/novapay/np-app.jpg", label: "np-app" },
  { src: "/deck/novapay/np-dog.jpg", label: "np-dog" },
  { src: "/deck/novapay/np-heart.jpg", label: "np-heart" },
  { src: "/deck/novapay/np-steps.jpg", label: "np-steps" },
  { src: "/deck/novapay/qr-instagram.svg", label: "qr-instagram" },
  { src: "/deck/novapay/sherlock.jpg", label: "sherlock" },
  { src: "/deck/novapay/tania-chair-bw.jpg", label: "tania-chair-bw" },
  { src: "/deck/novapay/tania-flip-bw.jpg", label: "tania-flip-bw" },
  { src: "/deck/novapay/tania-hall-bw.jpg", label: "tania-hall-bw" },
  { src: "/deck/novapay/tania-laptop-2.jpg", label: "tania-laptop-2" },
  { src: "/deck/novapay/tania-laptop-bw2.jpg", label: "tania-laptop-bw2" },
  { src: "/deck/novapay/tania-mic-2.jpg", label: "tania-mic-2" },
  { src: "/deck/novapay/tania-mic-bw.jpg", label: "tania-mic-bw" },
  { src: "/deck/novapay/tania-profile.jpg", label: "tania-profile" },
  { src: "/deck/novapay/tania.jpg", label: "tania" },
  { src: "/deck/novapay/trump.jpg", label: "trump" },
  { src: "/deck/novapay/whoopi.jpg", label: "whoopi" }
];
